Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - '**/*.pryrc'
    - '**/*.rake'
    - '.env'
    - '.simplecov'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
  Exclude:
    - 'db/schema.rb'
Documentation:
  Enabled: false
Lint/HandleExceptions:
  Exclude:
    - 'bin/*'
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'
Metrics/ClassLength:
  Exclude:
    - 'db/migrate/*'
Metrics/LineLength:
  Exclude:
    - 'db/migrate/*'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
Style/AutoResourceCleanup:
  Enabled: true
Style/CollectionMethods:
  Enabled: true
Style/Encoding:
  Enabled: true
Style/FirstArrayElementLineBreak:
  Enabled: true
Style/FirstHashElementLineBreak:
  Enabled: true
Style/FirstMethodArgumentLineBreak:
  Enabled: true
Style/FirstMethodParameterLineBreak:
  Enabled: true
Style/MultilineAssignmentLayout:
  Enabled: true
Style/OptionHash:
  Enabled: true
Style/StringMethods:
  Enabled: true
Style/SymbolArray:
  Enabled: true
Style/TrivialAccessors:
  Enabled: true
  ExactNameMatch: true
