#!/bin/sh
echo 'install-badge-dev-env: Auto-install development environment for BadgeApp.'

# Configure options.
system_install_prefix='sudo'


# If you modify this script, please check it with the "shellcheck"
# shell static analysis tool.
# The following enables some run-time error detection:
set -e -u


# Define globals and functions.

# This is the running list of system packages to install.
PACKAGES=''

# Add list of packages to the PACKAGES list. Rename packages as needed
add_pkg () {
  for p ; do
    if [ "$p" = '' ] || [ "$p" = '-' ] ; then continue ; fi
    PACKAGES="$PACKAGES $p"
  done
}

# Return true iff $1 is a command
is_command () {
  command -v "$1" > /dev/null
}

# Given a list of commands, return the first one that exists (if any)
find_command () {
  for f ; do
    if is_command "$f" ; then
      echo "$f"
      true
      return
    fi
  done
  # None found, return something useful.
  echo UNKNOWN
  false
}


# Main line.

if ! [ -f 'install-badge-dev-env' ] ; then
  echo 'Must run at top level.' >&2
  exit 1
fi

# First, figure out what package manager to use.
echo
echo 'STAGE 1: Determine the package manager to use.'

if [ "$(uname)" = "Darwin" ] ; then
  manager='brew'
  if ! is_command brew ; then
    echo 'Downloading and installing brew.'
    brew_url='https://raw.githubusercontent.com/Homebrew/install/master/install'
    ruby -e "$(curl -fsSL $brew_url)"
  fi
else
  # apt-get : Debian, Ubuntu
  # dnf : some Fedora
  # yum : Red Hat Enterprise Linux, CentOS, some Fedora
  # zypper : SuSE
  # emerge : Gentoo
  # pkg : *BSDs.  We're not trying ports vs. packages; patches welcome.
  # urpmi : Mageia/Mandriva
  manager=$(find_command apt-get dnf yum zypper emerge pkg urpmi)
  if [ "$manager" = 'UNKNOWN' ] ; then
    echo 'Could not find a system package manager.'
    exit 1
  fi
fi


if [ "$manager" = 'urpmi' ]; then
  installer="$manager"
else
  installer="$manager install"
fi

echo "Will use the installer command '$installer'"

# Now start adding packages. 
echo
echo 'STAGE 2: Identifying and install system packages'

# git should already be installed, but we'll make sure of it.
is_command git || add_pkg git

# Install a bootstrap version of Ruby, if we don't already have one.
# We'll actually install a specific version later, but this will help us
# bootstrap the installation and building of that version.
is_command ruby || add_pkg ruby

# SQLite3 database system, used in development for data storage
add_pkg sqlite3

# C compiler for rebuilding a specific version of ruby.
add_pkg gcc

echo 'About to install system packages with the command:'
echo "  $system_install_prefix $installer $PACKAGES"

# shellcheck disable=SC2086
$system_install_prefix $installer $PACKAGES


# Install rbenv, to let us select a specific version of ruby.
echo
echo 'STAGE 3: Install rbenv'

if is_command 'rvm' ; then
  echo 'WARNING: rvm installed, may be incompatible with rbenv.' >&2
fi

if is_command 'rbenv' ; then
  echo 'rbenv already installed.'
else
  git clone https://github.com/sstephenson/rbenv.git ~/.rbenv

  # ensure rbenv is on the PATH when running the rest of this script.
  export PATH="$HOME/.rbenv/bin:$PATH"

  # Make rbenv a permanent fixture.
  rbenv_set=0
  for f in .bashrc .bash_profile .profile
  do
    if [ -f "$HOME/$f" ] ; then
      if ! grep '\.rbenv/bin' > /dev/null ; then
        # shellcheck disable=SC2016
        echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> "$HOME/$f"
      fi
      rbenv_set=1
    fi
  done
  if [ $rbenv_set = 0 ] ; then
    echo 'Warning: Did not modify the PATH in a shell rc or profile.' >&2
  fi
fi

# This makes "bundle ..." use rbenv's version of Ruby:
if ! [ -e "$HOME/.rbenv/plugins/bundler" ] ; then
  git clone git://github.com/carsomyr/rbenv-bundler.git \
            "$HOME/.rbenv/plugins/bundler"
fi

# Force install Ruby 2.2.2 using rbenv.  This may cause a compile.
echo
echo 'STAGE 4: For this project, force install fixed version of ruby'

rbenv install --skip-existing 2.2.2
rbenv local 2.2.2 # In this directory AND BELOW, use Ruby 2.2.2 instead.

echo
echo 'STAGE 5: Install gems (including bundler and Rails)'

gem sources --add https://rubygems.org  # Ensure you're getting gems here
gem install bundler  # Install the "bundler" gem package manager.
rbenv rehash
bundle install       # Install gems we use in Gemfile.lock, including Rails

echo
echo 'STAGE 6: Set up database for development if necessary'

# Is the database already set up?
rails console > .rconsole <<END_OF_COMMANDS
def database_exists?
  db="database"
  ActiveRecord::Base.connection
rescue ActiveRecord::NoDatabaseError
  puts "#{db} not present"
else
  puts "#{db} present"
end
database_exists?
END_OF_COMMANDS

if grep 'database not present' .rconsole > /dev/null ; then
  echo 'Running "rake db:setup" - the database is not present'
  rake db:setup        # Setup database and seed it with dummy data
else
  echo 'Skipping "rake db:setup" - the database appears to be present'
fi

echo
echo 'FINAL STAGE: Test to see if it is working'

bin/rake
