#!/bin/sh
# Update Ruby.  If you're initiating this for the project, pass the
# new version as the first parameter - this will update and commit.
# If you're not initiative this for the project, provide no parameters -
# this will update as needed (to the version given in ".ruby-version").

# The following enables some run-time error detection:
set -e

if [ "$1" ] ; then
    ruby_version="$1"
else
    ruby_version="$(cat .ruby-version)"
fi

# Update ruby-build list
if [ "$(uname)" = 'Darwin' ] ; then
    brew update && brew upgrade ruby-build
else
    (cd "$HOME"/.rbenv/plugins/ruby-build && git pull)
fi
# Install with ruby-build
rbenv install "$ruby_version"
# Use new Ruby version if you are doing the first
if [ "$1" ]; then
    rbenv local "$ruby_version"
fi

# Make sure we're using the current "gem" system
gem update --system
# Tell rbenv about that
rbenv rehash
# Reinstall bundler for it
gem install bundler
# Tell rbenv about bundler
rbenv rehash
# Reinstall gems
bundle install
# Update rbenv commands
rbenv rehash

# Commit with a standard upgrade message then sign and allow message change,
# but only if local tests pass.
if [ "$1" ] && rake; then
    git commit -am "Upgrade to ruby $ruby_version"
    git commit --amend -s
fi
