#!/bin/sh

if [ "$1" ] ; then
    ruby_version="$1"
else
    ruby_version="$(cat .ruby-version)"
fi

# Update ruby-build list
(cd "$HOME"/.rbenv/plugins/ruby-build && git pull)
# Install with ruby-build
rbenv install "$ruby_version"
# Use new Ruby version if you are doing the first
if [ "$1" ]; then
    rbenv local "$ruby_version"
fi

# Reinstall bundler for it
gem install bundler
# Tell rbenv about bundler
rbenv rehash
# Reinstall gems
bundle install
# Update rbenv commands
rbenv rehash

# Commit with a standard upgrade message then sign and allow message change
if [ "$1" ]; then
    git commit -am "Upgrade to ruby $ruby_version"
    git commit --amend -s
fi
