source 'https://rubygems.org'

gem 'bcrypt', '3.1.10'
gem 'bootstrap-sass', '3.2.0.2'
gem 'bootstrap-switch-rails', '3.3.3'
gem 'bootstrap-will_paginate', '0.0.10'
gem 'bootstrap_form', '2.3.0'
gem 'faker', '1.5.0'
gem 'github_api', '0.12.4'
gem 'jbuilder', '2.3.1'
gem 'jquery-rails', '4.0.4'
gem 'jquery-ui-rails', '5.0.5'
gem 'omniauth-github', '1.1.1'
gem 'paper_trail', '4.0.0'
gem 'rails', '4.2.1'
gem 'sass-rails', '5.0.3'
gem 'turbolinks', '2.5.3'
gem 'uglifier', '2.7.1'
gem 'will_paginate', '3.0.7'

group :development, :test do
  gem 'pronto', '0.4.3'
  gem 'pronto-brakeman', '0.4.3'
  gem 'pronto-rails_best_practices', '0.4.0'
  gem 'pronto-rubocop', '0.4.6'
  gem 'pry-byebug', '3.2.0'
  gem 'spring', '1.3.6'
  gem 'sqlite3', '1.3.10'
  gem 'web-console', '2.2.1'
end

group :production do
  gem 'pg', '0.18.2'
  gem 'rails_12factor', '0.0.2'
end
